project:
  type: book

book:
  title: "Instructor Guide"
  subtitle: "Stat 20"
  date: today
  repo-url: https://github.com/stat20/instructor-guide
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - notes.qmd
    - slides.qmd

format:
  html:
    theme: cosmo
    number-depth: 1

execute:
  freeze: auto

