project:
  type: book

book:
  title: "Instructor Guide"
  subtitle: "Stat 20"
  date: today
  chapters:
    - index.qmd
    - notes.qmd
    - slides.qmd

format:
  html:
    theme: cosmo

execute:
  freeze: auto

